### ISSUE TITLE
Issue where Project is not linked to any Repos

### ISSUE THREAD

**Issue by gitstua** [timrogers/gh-migrate-project#255] opened 2024-06-12 22:32 UTC
👋  Hi @timrogers 

We were using this extension to export a project board and I noticed a minor bug

## Bug
It seems this [code](https://github.com/timrogers/gh-migrate-project/blob/829b2a9a329840b439d0d2362dcd5ef359ffe7a4/src/commands/export.ts#L295) in **export** produces 

```json
 "repositories": {
      "nodes": [
        null
      ],
      "totalCount": 1
    },
```
which causes an error in the **import**.

## Steps to reproduce
1. Create a GitHub Project at org level associated with no repositories
2. Export
3. Import
4. Error thrown

## Workaround
To workaround this I just manually updated the json to:
```json
 "repositories": {
      "nodes": [
      ],
      "totalCount": 1
    },
```

**Comment by timrogers** [comment] 2024-06-13 10:11
@gitstua Hey! :wave: I'm not able to reproduce this issue I'm afraid.

I created a new org-owner project, and I get an output like this, as expected:

```json
{
  "repositories": {
    "nodes": [],
    "totalCount": 0
  }
}
```

`null` being returned by the GraphQL API suggests that there is a repo attached to the project, but your token can't see it.

Are you able to reproduce the issue for a brand new project?

**Comment by timrogers** [comment] 2024-09-22 20:19
Closing due to lack of updates - feel free to reopen!

**Closed by timrogers** 2024-09-22 20:19 UTC
