### ISSUE TITLE
Migration fails if project is linked to repository

### ISSUE THREAD

**Issue by kmaehashi** [timrogers/gh-migrate-project#113] opened 2023-12-14 06:24 UTC
When migrating a project I get:

```
2023-12-14T06:13:35.919Z info: Linking 2 repositor[y|ies] to project...
2023-12-14T06:13:35.920Z info: Linking repository OUR-SOURCE-ORG/REPONAME (1/2)
Request failed due to following response errors:
 - You must have write access on this repository.
GraphqlResponseError: Request failed due to following response errors:
 - You must have write access on this repository.
    at /snapshot/dist/migrate-project.cjs
    at async addRepositoryToProject (/snapshot/dist/migrate-project.cjs)
    at async /snapshot/dist/migrate-project.cjs
    at async _Command.<anonymous> (/snapshot/dist/migrate-project.cjs)
```

It seems linked repositories (`jq .project.repositories project.json` in exported projects) are not translated and the tool is trying to link to the source repository instead of the new (destination) repository. I'd expect to respect `--repository-mappings-path` here.

**Comment by timrogers** [comment] 2023-12-14 17:33
@kmaehashi 👋 Hi there!

Looking at the code, I'm pretty convinced that it does try to link the correct repository, and it's just the logging that is confusing:

https://github.com/timrogers/gh-migrate-project/blob/8466276e19382d6a59687cd052d5d35c6a3b254f/src/commands/import.ts#L869-L873

I've created an issue for that [here](https://github.com/timrogers/gh-migrate-project/issues/115), and will fix it now.

My gut feeling is that the problem here is a permissions problem affecting access to the target repository in your repository mappings file.

What are the permissions on your access token? Are you using a traditional token or a new token with fine-grained permissions? (e.g. from a GitHub App or beta PAT).

**Comment by timrogers** [comment] 2023-12-14 17:47
Logging fixed in [v0.5.1](https://github.com/timrogers/gh-migrate-project/releases/tag/v0.5.1) ✅

**Comment by kmaehashi** [comment] 2023-12-15 01:27
Hi Tim, thanks as always for the quick response!

I found that the problem happens when a repository is linked but no items from that repository are added to the project. The real problem is that the generated `repository-mappings.csv` does not contain such repositories because the repository list is computed only from project items.

https://github.com/timrogers/gh-migrate-project/blob/caef98d2a87fd1b55bb9454d2d11957c05cd378f/src/commands/export.ts#L520-L530

Do you think it makes sense to add linked repositories (which has no project items) to the CSV as well?

**Comment by timrogers** [comment] 2023-12-15 10:11
Hmm, looking at the code it should skip if there is no mapping 🤔, so I'm unsure what the problem is. I will try to reproduce with your instructions.

**Comment by kmaehashi** [comment] 2023-12-15 11:41
When doing `gh migrate-project export`, if the project has no items and is linked to a repository `SRC-ORG/REPO`, `repository-mappings.csv` will contain no rows. Then when doing `gh migrate-project import`, the tool tries to link `SRC-ORG/REPO`, because no mapping (from `SRC-ORG/REPO` to `DST-ORG/REPO`) is specified in the CSV. The reason why I get `You must have write access on this repository` error is that the PAT used for import has permission on `DST-ORG` but not on `SRC-ORG`.

**Comment by timrogers** [comment] 2023-12-15 13:01
That still doesn't ring true for me, because in the case where there is no mapping, we should skip the linkage:

https://github.com/timrogers/gh-migrate-project/blob/caef98d2a87fd1b55bb9454d2d11957c05cd378f/src/commands/import.ts#L853-L858

It's definitely possible that there is something wrong with this though! I am going to try it now, and I will also look at some improvements to verbose mode (`--verbose`) to allow us to see the GraphQL queries, which will make debugging way easier.

**Comment by timrogers** [comment] 2023-12-15 13:02
(If the above "skip" condition is working as expected, I would expect to see a "Skipping source repository..." log entry instead of a "Linking repository..." log entry. It's definitely possible that there's a bug!

**Comment by kmaehashi** [comment] 2023-12-15 13:22
Thanks for the detailed insights, Tim. Your assessment looks legit... I'll try reproducing again when I have time! :pray:

**Comment by timrogers** [comment] 2023-12-15 13:52
I just tried this myself and I got the "Skipping source repository..." message, as I suspected:

```
2023-12-15T13:50:49.938Z info: Linking 1 repositor[y|ies] to project...
2023-12-15T13:50:49.939Z warn: Skipping source repository timrogers/gh-migrate-project because there is no repository mapping
```

I think there probably is a bug here, but I don't know what it is 🙏 

I'm going to release a new version with a better `--verbose` mode to make this easier to debug. The new version will log request response and bodies so you can see exactly what is happening. I'll share a link here once it's released.

**Comment by timrogers** [comment] 2023-12-15 13:56
[v0.6.0](https://github.com/timrogers/gh-migrate-project/releases/tag/v0.6.0) is ready to try when you have a chance - in `--verbose` mode, it will log requests and responses, so you can see exactly what is happening under the hood.

**Comment by timrogers** [comment] 2024-02-05 06:57
I'm going to close this as I haven't heard back from you, but feel free to add a comment if you still need help.

**Closed by timrogers** 2024-02-05 06:57 UTC
